version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      REDIS_DBNAME: "ing"
      REDIS_USER: "admin"
      REDIS_PASSWORD: "admin"
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
